[package]
name = "xwax-sys"
version = "0.1.0"
edition = "2021"
links = "xwax"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.64.0"
cc = "1.0.79"
